### ISSUE TITLE
author order?

### ISSUE THREAD

**Issue by LucyMcGowan** [LucyMcGowan/causal-inference-in-R#1]

**Comment by tgerke** [comment]
To my knowledge, textbook author ordering doesn't follow the academic journal norms of last author being a senior/project PI; rather, it's linear ordering according to intellectual/content contribution. Is that your understanding as well? If so, I was last to the party (you both have the fundamental contribution of vision setting this thing), so I should go last as the lowest ranking contributor.

**Comment by malcolmbarrett** [comment]
I reckon that would result in: me, Lucy, Travis

**Comment by LucyMcGowan** [comment]
Fine by me! Also technically alphabetical B, DM, G :sweat_smile: 🎉

**Comment by tgerke** [comment]
Awesome! 😄 👍
