### ISSUE TITLE
Domain name

### ISSUE THREAD

**Issue by malcolmbarrett** [LucyMcGowan/causal-inference-in-R#6]
For the rendered version of the book. I think we should get one rather than linking to one of our websites

**Comment by LucyMcGowan** [comment]
Totally agree!

**Comment by tgerke** [comment]
Yes! Do you have suggestions? Just checked and causalinferencer.com is available.

**Comment by malcolmbarrett** [comment]
Sorry, forgot to post here: I bought r-causal.org!
